### PR TITLE
Fix tests on Travis CI

### PR DESCRIPTION
**Pull request by omus**
Attempting to get the Travis CI tests passing again.

### CODE REVIEW

**Comment by omus** [comment]
Tests are now working on Julia 0.6. Details so far:

Supported using an environmental variable ("ODBC_DSN") to use in the tests. This allows us to bypass the test parts that are hardcode for Jacob's system.

Enable local-infile for the ODBC client. Due to security restrictions in MySQL the [LOAD DATA LOCAL](https://dev.mysql.com/doc/refman/5.7/en/load-data-local.html) statement will only work if it is enabled on both the server and the client. The setting was enabled on the server but not on the client. To enable the setting on the client for ODBC we need to have the ODBC DSN use the ["my.cnf"](https://dev.mysql.com/doc/refman/5.7/en/option-files.html) files via the ["Option" parameter](https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-connection-parameters.html#codbc-dsn-option-flags) being set to 65536 ("USE_MYCNF").

**Comment by omus** [comment]
I'm allowing failures on the Julia nightly for Travis as it shouldn't be required and currently it is failing due to a build issue with SpecialFunctions.jl:

```
LoadError: LoadError: MethodError: Cannot `convert` an object of type Char to an object of type Symbol
This may have arisen from a call to the constructor Symbol(...),
since type constructors fall back to convert methods.
in expression starting at /home/travis/.julia/v0.7/SpecialFunctions/deps/binaries.jl:37
in expression starting at /home/travis/.julia/v0.7/SpecialFunctions/deps/build.jl:6
```

**Comment by omus** [comment]
Behold! The glorious green checkmarks have returned!

**Comment by quinnj** [comment]
This is marvelous. Thanks so much for your help here.

**Pull request merged**
