### PR TITLE
make the API pure UTF-8

### PR DESCRIPTION
**Pull request by StefanKarpinski**
This is probably the more reasonable change that makes everything UTF-8 and addresses https://github.com/quinnj/ODBC.jl/issues/67 for me. However, the question is whether this will work with all drivers or if some of them *require* UTF-16. @jakebolewski, perhaps you can chime in since it seems like you may have introduced some of the UTF-16 stuff that I'm now removing.

### CODE REVIEW

**Comment by phlpn** [comment]
This fixes #67 for me. I'm using 64 bit windows 7.

**Comment by MoreCoffee12** [comment]
I know this an old thread, but this issue just came up for me.  These lines resulted in a query that was twice as long as my actual string so I got the "invalid UTF-8 sequence" error. 

    #Connect to fault database (pre-defined Windows DSN in ODBC Manager)
    faultconn = ODBC.connect("Box"; usr="", pwd="")
    # define the query and execute it
    sql_query = "SELECT TOP 100 WaveformDescriptionID, WaveformMalfunctionID FROM           
    dbo.Waveforms"
    queryframe = query(ascii(sql_query),faultconn)

I went to my `backend.jl` file and removed the `utf16(...)` cast from `ODBCQueryExecute` as mentioned by @killerswan in #67.  That seems to have fixed the problem.  My query string at the MSSQL server is correct.  Should this have worked (am I missing something in my code or calls)?  I see it on the TODO of the repository, is the issue still being worked?  
 
My client machine is running Windows 8.1 (64-bit) and I am connecting to MSSQL 2008 R2 server which is running Windows 7, all 64-bit.  My package information is below.

    6 required packages:
    - DataFrames                    0.6.6
    - Gadfly                        0.3.12
    - IJulia                        0.2.5
    - ODBC                          0.3.10 
    - PyPlot                        1.5.3
    - RDatasets                     0.1.2

**Comment by killerswan** [comment]
Ahhh, I went out of town and then flaked out on doing a pull req. for it, at least!

**Comment by niczky12** [comment]
I've had  issues with this on Windows and as @MoreCoffee12 pointed out, removing the UTF8 casting on line 42 in backend.jl solved the issue.
Can this casting be set only to execute on unix machines? That could help a lot of people.

This also fixed issue #90 for me.

**Comment by ViralBShah** [comment]
@quinnj Does this get addressed in the overhaul branch? Also - people keep wanting these fixes for 0.4 as well.

**Comment by StefanKarpinski** [comment]
This problem is not fixed. My working theory here is that if you use a Windows database from a Windows system everything is fine and if you use a UNIX database from a UNIX system, everything is fine. But Summer Road is using a Windows database with a UNIX system and it's broken. Since Windows uses UTF-16 for its APIs while UNIX uses UTF-8 for its APIs, I suspect that there some code that decides whether to use UTF-16 or UTF-8 based on the client operating system when it should be deciding based on the server operating system.

**Comment by quinnj** [comment]
should be resolved by 7ae7ebfac60ed3ffb1ccefd552993a3073f8b77b

**Pull request closed without merging**
