### PR TITLE
Harsha/testing

### PR DESCRIPTION
**Pull request by bmharsha**
I've implemented following functionalities 

1)  Added more tests cases to runtests.jl such that ODBC.jl will be tested for following operations in different situations: Create, Insert, Select, Update, Grant, Drop, Commit, Rollback, START TRANSACTION.

2)  Added Negative test cases for aforementioned operations 

3)  Added a function to cross check the behaviour of ODBC.jl , runtest.jl raises an issue if the behaviour is unexpected.

4)  Replaced file ".travis.yml" , current script installs UnixODBC and configures it to run the tests on MySQL database

5)  Added Datasets folder which contains expected results for the queries being tested in runtests.jl

6)  Added a file named “odbc.ini” which configures UnixODBC on Travis server

### CODE REVIEW

**Comment by ViralBShah** [comment]
These should have been squashed before committing.

**Comment by StefanKarpinski** [comment]
Yeah, this is some really unfortunate history to keep around forever :-\

**Comment by ScottPJones** [comment]
Is there any way of squashing after it has been moved into a master branch?

**Comment by ViralBShah** [comment]
@StefanKarpinski You are our resident git expert when it comes to these things.

**Comment by StefanKarpinski** [comment]
You can squash master but that's a bad idea. Once something is on a public branch, it's best not to change it.

**Comment by quinnj** [comment]
Yeah, definitely unfortunate. @bmharsha, please ping other collaborators/owners in the future before merging.

**Pull request merged**
